name: Build and Deploy Spring Boot App
on:
  push:
    branches:
      - master
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up JDK 17 
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build with Maven
        run: mvn clean package -DskipTests
        
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
          
      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            echo "=== Starting deployment ==="
            
            # Clean environment variables (remove newlines and whitespace)
            DB_USER_CLEAN=$(echo "${{ secrets.DB_USER }}" | tr -d '\n\r' | xargs)
            DB_PASSWORD_CLEAN=$(echo "${{ secrets.DB_PASSWORD }}" | tr -d '\n\r' | xargs)
            DB_URL_CLEAN=$(echo "${{ secrets.DB_URL }}" | tr -d '\n\r' | xargs)
            
            echo "Cleaned environment variables"
            echo "DB_USER length: ${#DB_USER_CLEAN}"
            echo "DB_PASSWORD length: ${#DB_PASSWORD_CLEAN}"
            echo "DB_URL length: ${#DB_URL_CLEAN}"
            
            # Pull the latest Docker image
            echo "Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            
            # Stop and remove existing container if it exists
            echo "Stopping existing container..."
            sudo docker stop my-spring-app || true
            sudo docker rm my-spring-app || true
            
            # Run the new container with cleaned environment variables
            echo "Starting new container..."
            sudo docker run -d \
              --name my-spring-app \
              -p 8080:8080 \
              -e DB_USER="$DB_USER_CLEAN" \
              -e DB_PASSWORD="$DB_PASSWORD_CLEAN" \
              -e DB_URL="$DB_URL_CLEAN" \
              --restart unless-stopped \
              --health-cmd="curl -f http://localhost:8080/actuator/health || exit 1" \
              --health-interval=30s \
              --health-timeout=10s \
              --health-retries=3 \
              ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
            
            # Wait for container to start
            echo "Waiting for container to start..."
            sleep 10
            
            # Check if container is running
            if sudo docker ps | grep -q my-spring-app; then
              echo "✅ Container started successfully"
              sudo docker logs --tail 20 my-spring-app
            else
              echo "❌ Container failed to start"
              sudo docker logs my-spring-app
              exit 1
            fi
            
            # Clean up old Docker images to save space
            echo "Cleaning up old images..."
            sudo docker image prune -f
            
            echo "=== Deployment completed ==="