name: Build and Push Docker Image
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17 
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest .
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: | 
            # Set environment variables
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export DB_URL="${{ secrets.DB_URL }}"

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

            # Stop and remove existing container if it exists
            sudo docker stop my-spring-app || true
            sudo docker rm my-spring-app || true

            # Run the new container with environment variables
            sudo docker run -d \
              --name my-spring-app \
              -p 8080:8080 \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_URL="${{ secrets.DB_URL }}" \
              --restart unless-stopped \
              ${{ secrets.DOCKER_USERNAME }}/my-spring-app:latest

            # Clean up old Docker images to save space
            sudo docker image prune -f